### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by the-byte-bender** [abdallah-hader/advanced_notepad#2]
Hello,
I was thinking it might be a good idea to add a license to this repo. I'm thinking the gpl would be a good fit. Because It is a copyleft license, which means that any derivatives of your code must also be licensed under the gpl. This protects your code from being used in proprietary projects.
What do you think?

**Comment by MesterPerfect** [comment]
@Meatbag93
hi 
General Public License has been added to Advanced Notepad
thanks
